# Core
OPENAI_API_KEY
ALLOWED_HOSTS=chatbay.site,i.postimg.cc,cdn.chatbay.site
FLASK_ENV=production
PYTHONUNBUFFERED=1

# Dropbox OAuth 2 Refresh Flow
DROPBOX_APP_KEY
DROPBOX_APP_SECRET
DROPBOX_REFRESH_TOKEN
DROPBOX_ACCESS_TOKEN   # (legacy optional)

# Folder setup
DROPBOX_IMAGE_FOLDER=/ebay
DROPBOX_CSV_FOLDER=/csv
DROPBOX_INCLUDE_SUBFOLDERS=true
